In [1]:
import pandas as pd

# 데이터 전처리

In [4]:
#파일불러오기
df = pd.read_csv("../raw_data/5.112신고.csv")
df.head()

         date jur_stn report_sx    inc_info
0  20180603.0    서울서부        남성        분실습득
1  20180603.0    서울송파        여성          폭력
2  20180603.0    서울강서        남성          소음
3  20180603.0   서울영등포        여성  실종(실종아동 등)
4  20180603.0    서울강서        남성        상담문의

In [5]:
#데이터 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9229111 entries, 0 to 9229110
Data columns (total 4 columns):
 #   Column     Dtype
---  ------     -----
 0   date       float64
 1   jur_stn    object
 2   report_sx  object
 3   inc_info   object
dtypes: float64(1), object(3)
memory usage: 281.7+ MB

In [6]:
#결측치 파악
df.isnull().sum()

date              0
jur_stn           0
report_sx      2190
inc_info     145216
dtype: int64

In [7]:
#날짜데터 float -> str로 조정
df["date"] = df["date"].astype(int).astype(str)

In [8]:
#컬럼명 변경
df.rename(columns = {"jur_stn":"관할서"},inplace = True)

In [9]:
# 관할서에 "경찰서" 붙이기
df["관할서"] = df["관할서"]+"경찰서"
df.head()

       date       관할서 report_sx    inc_info
0  20180603   서울서부경찰서        남성        분실습득
1  20180603   서울송파경찰서        여성          폭력
2  20180603   서울강서경찰서        남성          소음
3  20180603  서울영등포경찰서        여성  실종(실종아동 등)
4  20180603   서울강서경찰서        남성        상담문의

In [10]:
# 관할서명  수정
df["관할서"] = df["관할서"].str.replace("마산", "경남마산")                                     
df["관할서"] = df["관할서"].str.replace("창원", "경남창원")
df["관할서"] = df["관할서"].str.replace("수원", "경기수원")
df["관할서"] = df["관할서"].str.replace("진주", "경남진주")
df["관할서"] = df["관할서"].str.replace("진해", "경남진해")
df["관할서"] = df["관할서"].str.replace("세종", "충남세종")

In [11]:
df.head()

       date       관할서 report_sx    inc_info
0  20180603   서울서부경찰서        남성        분실습득
1  20180603   서울송파경찰서        여성          폭력
2  20180603   서울강서경찰서        남성          소음
3  20180603  서울영등포경찰서        여성  실종(실종아동 등)
4  20180603   서울강서경찰서        남성        상담문의

In [12]:
#연도별 데이터 생성 및 인덱스 재설정
df_2018 = df[df["date"].str.contains("2018")].reset_index(drop = True)
df_2019 = df[df["date"].str.contains("2019")].reset_index(drop = True)
df_2020 = df[df["date"].str.contains("2020")].reset_index(drop = True)
df_2021 = df[df["date"].str.contains("2021")].reset_index(drop = True)

In [13]:
#2018, 관할서별 신고수 파악
df_2018_dec = pd.DataFrame(df_2018.groupby(by="관할서", sort=True).count()["date"]).reset_index()
df_2018_dec

          관할서   date
0   경기수원남부경찰서  66800
1   경기수원서부경찰서  44330
2   경기수원중부경찰서  50500
3   경남마산동부경찰서  24228
4   경남마산중부경찰서  22123
5     경남진주경찰서  39459
6     경남진해경찰서  14577
7   경남창원서부경찰서  25072
8   경남창원중부경찰서  26456
9     서울강남경찰서  67951
10    서울강동경찰서  59356
11    서울강북경찰서  52162
12    서울강서경찰서  68216
13    서울관악경찰서  78887
14    서울광진경찰서  60641
15    서울구로경찰서  59554
16    서울금천경찰서  46711
17   서울남대문경찰서  20457
18    서울노원경찰서  63020
19    서울도봉경찰서  38572
20   서울동대문경찰서  57470
21    서울동작경찰서  47448
22    서울마포경찰서  76246
23    서울방배경찰서  20023
24   서울서대문경찰서  52222
25    서울서부경찰서  24675
26    서울서초경찰서  55285
27    서울성동경찰서  39544
28    서울성북경찰서  30359
29    서울송파경찰서  86985
30    서울수서경찰서  41059
31    서울양천경찰서  50755
32   서울영등포경찰서  65100
33    서울용산경찰서  54121
34    서울은평경찰서  38782
35    서울종로경찰서  19712
36    서울종암경찰서  22973
37    서울중랑경찰서  65828
38    서울중부경찰서  30705
39    서울혜화경찰서  25126
40    충남세종경찰서  12102

In [33]:
#2019, 관할서별 신고수 파악
df_2019_dec = pd.DataFrame(df_2019.groupby(by="관할서", sort=True).count()["date"]).reset_index()
df_2019_dec

          관할서    date
0   경기수원남부경찰서  126370
1   경기수원서부경찰서   76359
2   경기수원중부경찰서   93040
3   경남마산동부경찰서   49968
4   경남마산중부경찰서   39845
5     경남진주경찰서   72730
6     경남진해경찰서   38863
7   경남창원서부경찰서   42807
8   경남창원중부경찰서   54823
9     서울강남경찰서  116427
10    서울강동경찰서  100171
11    서울강북경찰서   85688
12    서울강서경찰서  136676
13    서울관악경찰서  136098
14    서울광진경찰서  100702
15    서울구로경찰서  102948
16    서울금천경찰서   71521
17   서울남대문경찰서   34795
18    서울노원경찰서  104305
19    서울도봉경찰서   62552
20   서울동대문경찰서  100029
21    서울동작경찰서   81691
22    서울마포경찰서  126014
23    서울방배경찰서   30495
24   서울서대문경찰서   84557
25    서울서부경찰서   42044
26    서울서초경찰서   96617
27    서울성동경찰서   67117
28    서울성북경찰서   49097
29    서울송파경찰서  146751
30    서울수서경찰서   86499
31    서울양천경찰서   83728
32   서울영등포경찰서  135579
33    서울용산경찰서   88576
34    서울은평경찰서   63394
35    서울종로경찰서   51928
36    서울종암경찰서   38220
37    서울중랑경찰서  110242
38    서울중부경찰서   49730
39    서울혜화경찰서   42919
40    충남세종경찰서   21278

## 20년도 신고수 데이터는 추후 test를 위해 따로 저장

In [27]:
## 근데 20년도는 세종경찰서 데이터가  없다...
df_2020[df_2020["관할서"].str.contains("충남세종경찰서")]

Empty DataFrame
Columns: [date, 관할서, report_sx, inc_info]
Index: []

In [16]:
#2020, 관할서별 신고수 파악
df_2020_dec = pd.DataFrame(df_2020.groupby(by="관할서", sort=True).count()["date"]).reset_index()
df_2020_dec

df_2020_dec.to_csv("../20년도_예측을위한_변수data/20년도_관할서별_신고수")

## 18,19병합

In [39]:
# 병합
df_dec_merge = pd.merge(df_2018_dec, df_2019_dec, on=["관할서"]).rename(columns = {"date_x":"18_신고수","date_y":"19_신고수"})
df_dec_merge

          관할서  18_신고수  19_신고수
0   경기수원남부경찰서   66800  126370
1   경기수원서부경찰서   44330   76359
2   경기수원중부경찰서   50500   93040
3   경남마산동부경찰서   24228   49968
4   경남마산중부경찰서   22123   39845
5     경남진주경찰서   39459   72730
6     경남진해경찰서   14577   38863
7   경남창원서부경찰서   25072   42807
8   경남창원중부경찰서   26456   54823
9     서울강남경찰서   67951  116427
10    서울강동경찰서   59356  100171
11    서울강북경찰서   52162   85688
12    서울강서경찰서   68216  136676
13    서울관악경찰서   78887  136098
14    서울광진경찰서   60641  100702
15    서울구로경찰서   59554  102948
16    서울금천경찰서   46711   71521
17   서울남대문경찰서   20457   34795
18    서울노원경찰서   63020  104305
19    서울도봉경찰서   38572   62552
20   서울동대문경찰서   57470  100029
21    서울동작경찰서   47448   81691
22    서울마포경찰서   76246  126014
23    서울방배경찰서   20023   30495
24   서울서대문경찰서   52222   84557
25    서울서부경찰서   24675   42044
26    서울서초경찰서   55285   96617
27    서울성동경찰서   39544   67117
28    서울성북경찰서   30359   49097
29    서울송파경찰서   86985  146751
30    서울수서경찰서   41059   86499
31    서울양천경찰서   50755   83728
32   서울영등포경찰서   65100  135579
33    서울용산경찰서   54121   88576
34    서울은평경찰서   38782   63394
35    서울종로경찰서   19712   51928
36    서울종암경찰서   22973   38220
37    서울중랑경찰서   65828  110242
38    서울중부경찰서   30705   49730
39    서울혜화경찰서   25126   42919
40    충남세종경찰서   12102   21278

In [40]:
#파일저장
df_dec_merge.to_csv("전처리완성본/5_관할서별_신고수")